-- 02-load.sql - Load generated CSVs into PAPERTRAIL.RAW
-- Idempotent: TRUNCATE + COPY ensures repeatable full reload.
-- Prerequisite: 01-raw.sql (creates tables), stage with uploaded CSVs.
--
-- Before running:
--   1. Upload CSVs to stage:
--      PUT 'file:///.../data/out/<table>.csv' @PAPERTRAIL.RAW.PAPERTRAIL_LOAD/<table>/ AUTO_COMPRESS=TRUE OVERWRITE=TRUE
--   2. Do NOT upload ground_truth.csv - it is the held-out answer key.

USE DATABASE PAPERTRAIL;
USE SCHEMA RAW;
USE WAREHOUSE PAPERTRAIL_WH;

-- Stage (idempotent)
CREATE STAGE IF NOT EXISTS PAPERTRAIL_LOAD
  FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'None')
    EMPTY_FIELD_AS_NULL = TRUE
  )
  COMMENT = 'Internal stage for loading generated CSVs into RAW tables';

-- File format shorthand
CREATE OR REPLACE FILE FORMAT PAPERTRAIL_CSV
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'None')
  EMPTY_FIELD_AS_NULL = TRUE;

-- ── Load each table (truncate first for idempotency) ───────

TRUNCATE TABLE IF EXISTS COUNTERPARTY;
COPY INTO COUNTERPARTY
  FROM @PAPERTRAIL_LOAD/counterparty/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ACCOUNT;
COPY INTO ACCOUNT
  FROM @PAPERTRAIL_LOAD/account/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS TRANSACTION;
COPY INTO TRANSACTION
  FROM @PAPERTRAIL_LOAD/transaction/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ALERT;
COPY INTO ALERT
  FROM @PAPERTRAIL_LOAD/alert/
  PATTERN = '.*alert\.csv.*'
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS ALERT_TRANSACTION;
COPY INTO ALERT_TRANSACTION
  FROM @PAPERTRAIL_LOAD/alert_transaction/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS CASE_INVESTIGATION;
COPY INTO CASE_INVESTIGATION
  FROM @PAPERTRAIL_LOAD/case_investigation/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS CASE_ALERT;
COPY INTO CASE_ALERT
  FROM @PAPERTRAIL_LOAD/case_alert/
  PATTERN = '.*case_alert\.csv.*'
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS WATCHLIST_ENTRY;
COPY INTO WATCHLIST_ENTRY
  FROM @PAPERTRAIL_LOAD/watchlist_entry/
  PATTERN = '.*watchlist_entry\.csv.*'
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS WATCHLIST_SCREENING_RESULT;
COPY INTO WATCHLIST_SCREENING_RESULT
  FROM @PAPERTRAIL_LOAD/watchlist_screening_result/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS REGULATORY_DOCUMENT;
COPY INTO REGULATORY_DOCUMENT
  FROM @PAPERTRAIL_LOAD/regulatory_document/
  PATTERN = '.*regulatory_document\.csv.*'
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE IF EXISTS REGULATORY_DOCUMENT_CLAUSE;
COPY INTO REGULATORY_DOCUMENT_CLAUSE
  FROM @PAPERTRAIL_LOAD/regulatory_document_clause/
  FILE_FORMAT = PAPERTRAIL_CSV
  ON_ERROR = ABORT_STATEMENT;
